### ISSUE TITLE
Incorrect version in DESCRIPTION file for v1.99.1

### ISSUE THREAD

**Issue by nathankw** [hms-dbmi/scde#26]
I downloaded the latest release 1.99.1 from http://hms-dbmi.github.io/scde/package.html, however, in the DESCRIPTION file it says that the version is 0.99.1. Is this indeed version 1.99.1, and just a case where the version number wasn't updated?

**Comment by JEFworks** [comment]
Hi Nathan,
It is indeed version 1.99.1. We had to temporarily change to 0.99.1 for Bioconductor submission due to new package requirements. Apologies for the confusion. Will fix.
Best,
Jean

**Comment by JEFworks** [comment]
Fixed in commit f095eb8ccda015cdb14f1ca2ba07c6c31004c545. Thanks Nathan!
