### ISSUE TITLE
Problem with applying scde to data with more than 2 groups

### ISSUE THREAD

**Issue by ulah** [hms-dbmi/scde#28]
Sry, wasn't an issue, I just misunderstood the vignette ;) Can be deleted...

**Comment by ulah** [comment]
Sry, I didn't see the possibility to include NA's in the factor... the issue can be deleted...

**Comment by ulah** [comment]
I also tried to use NA's in the factor as suggested in the vignette ("The factor elements correspond to the rows of the model matrix (o.ifm), and can contain NA values (i.e. cells that won't be included in either group)."), but they are treated as a separate lvl in the factor: "ERROR: wrong number of levels in the grouping factor (group1 group2 NA), but must be two."

**Comment by JEFworks** [comment]
It looks like for your grouping vector, you are setting some cells to NA then converting that vector into a factor so ‘NA’ is being treated as a factor grouping. You will need to convert to a factor first, then set cells to NA such that `levels(grouping_factor)` only has 2 levels. 

ex.
```
> groups <- factor(gsub("(MEF|ESC).*", "\\1", rownames(o.ifm)), levels  =  c("ESC", "MEF"))
> names(groups) <- row.names(o.ifm)
> 
> groups
ESC_10 ESC_11 ESC_12 ESC_13 ESC_14 ESC_15 ESC_16 ESC_17 ESC_18 ESC_19  ESC_1 ESC_20 
   ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC 
ESC_21 ESC_22 ESC_23 ESC_24 ESC_25 ESC_26 ESC_27 ESC_28 MEF_49 MEF_50 MEF_51 MEF_52 
   ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    MEF    MEF    MEF    MEF 
MEF_53 MEF_54 MEF_55 MEF_56 MEF_57 MEF_58 MEF_59 MEF_60 MEF_61 MEF_62 MEF_63 MEF_64 
   MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF 
MEF_65 MEF_66 MEF_67 MEF_68 
   MEF    MEF    MEF    MEF 
Levels: ESC MEF
> groups[1] <- NA
> groups
ESC_10 ESC_11 ESC_12 ESC_13 ESC_14 ESC_15 ESC_16 ESC_17 ESC_18 ESC_19  ESC_1 ESC_20 
  <NA>    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC 
ESC_21 ESC_22 ESC_23 ESC_24 ESC_25 ESC_26 ESC_27 ESC_28 MEF_49 MEF_50 MEF_51 MEF_52 
   ESC    ESC    ESC    ESC    ESC    ESC    ESC    ESC    MEF    MEF    MEF    MEF 
MEF_53 MEF_54 MEF_55 MEF_56 MEF_57 MEF_58 MEF_59 MEF_60 MEF_61 MEF_62 MEF_63 MEF_64 
   MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF    MEF 
MEF_65 MEF_66 MEF_67 MEF_68 
   MEF    MEF    MEF    MEF 
Levels: ESC MEF
```

**Comment by ulah** [comment]
yes, that was the problem, thanks!
