### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by rekado** [hms-dbmi/scde#38]
The DESCRIPTION file declares the GPL version 2 to be the license for SCDE, but the license.txt file is a non-free license incompatible with the GPL.  Which license really applies to SCDE?

**Comment by JEFworks** [comment]
Apologies for the confusion. Our intent is to provide a free copyleft open-source license intended for noncommercial/academic use as well as allow the possibility of derivative proprietary applications through multi-licensing.

**Comment by rekado** [comment]
Thank you for your response.  I'm afraid I'm still confused by the statement "free copyleft open-source license intended for noncommercial/academic use", because the GPL grants the use for any purpose, including commercial use:

    https://www.gnu.org/licenses/gpl-faq.en.html#NoMilitary

The  copyright holder (i.e. the authors including all contributors in case there is no copyright assignment process) always has the right to grant other licenses (e.g. for sale) to certain users, including a custom proprietary license that permits the use in proprietary software (which is not permitted by the GPL).  I assume that this is what you mean by multi-licensing.

Unfortunately, a license that only permits non-commercial or academic use is not considered an Open Source or Free Software license.  This would prevent all free software distributions from including or distributing the package.

    https://www.gnu.org/philosophy/programs-must-not-limit-freedom-to-run.html
    https://opensource.org/docs/osd (point 6)

It would be great if you could clarify that the GPL does indeed apply for all purposes and that the choice of a proprietary license (e.g. after paying money) is optional.

Thank you!
