### ISSUE TITLE
Significant corrected Z-score?

### ISSUE THREAD

**Issue by livnatje** [hms-dbmi/scde#50]
Thank you for providing this great pipeline!

Could you recommend which cutoff to use?
What would be considered a significant corrected Z-score?

**Comment by JEFworks** [comment]
Of course. Thanks for using it!

I would generally recommend a cutoff of 1.96 corresponding to a p-value of 0.05 for a two-tailed test. 

Here is a good visualization of how p-values relate to z-scores and relate to normal distributions:
![image](https://user-images.githubusercontent.com/8975944/29230167-c1aab27e-7eaf-11e7-94dc-d448a7981789.png)
(http://pro.arcgis.com/en/pro-app/tool-reference/spatial-statistics/what-is-a-z-score-what-is-a-p-value.htm)

If you are looking for strong markers, a z-score of 3 may be more appropriate. If you are doing gene set enrichment afterwards or looking for general trends among your differentially expressed genes, a z-score of 1.28 may be more appropriate.

**Comment by livnatje** [comment]
Thank you Jean! So, just to make sure, cZ would be after multiple hypotheses correction, so a cutoff of  1.96 would make sense, right?

**Comment by JEFworks** [comment]
Yes exactly! You will likely want to consider both below -1.96 (significantly downregulated) and above 1.96 (significantly upregulated) ie. absolute cZ > 1.96

**Comment by poryaparvizi** [comment]
Hi Jean,
I have a question that in `scde.expression.difference` when i use batch, the result gives `batch.corrected`, `batch.error` and `results`. which one should i use to find significant in differential expression?
