### ISSUE TITLE
Differing Results in SCDE Tutorial

### ISSUE THREAD

**Issue by adamnc2** [hms-dbmi/scde#69]
Hi all,

I am a beginner to R and I am currently trying to run the provided SCDE tutorial code in RStudio. I noticed that when I complete the tutorial and load o.ifm directly (using data(o.ifm)), I get results that are fairly close to the example results within the tutorial. However, when I calculate o.ifm with the code provided in the tutorial (using scde.error.models), my answers vary greatly from the example results. I have included the results of both methods below:

**Using data(o.ifm):**

![data o ifm](https://user-images.githubusercontent.com/35505034/41544815-46817c8e-72df-11e8-8cf7-266463c3d4a5.PNG)

**Using o.ifm <- scde.error.models(counts = cd, groups = sg, n.cores = 1, threshold.segmentation = TRUE, . . . :**

![coded_o ifm](https://user-images.githubusercontent.com/35505034/41544954-a76332d6-72df-11e8-97d2-49e3055b04ce.PNG)

Please let me know if you have any idea why this difference is happening, and I apologize if there is an obvious solution to this problem. Thank you in advance for any help!

**Comment by JEFworks** [comment]
Closing due to issue being duplicated in Google Groups: https://groups.google.com/forum/embed/?place=forum/singlecellstats&showsearch=true&showpopout=true&showtabs=false&parenturl=http%3A%2F%2Fhms-dbmi.github.io%2Fscde%2Fhelp.html#!topic/singlecellstats/GMMDvABvpYA
