### ISSUE TITLE
Error in t.default(pmat1) : argument is not a matrix

### ISSUE THREAD

**Issue by YingMa1993** [hms-dbmi/scde#70]
When I try to calculate the  difference posterior, it showed the error:
Error in t.default(pmat1) : argument is not a matrix

I checked the format of the dataset, everything looks reasonable as the sample dataset. 

Any suggestions?

**Comment by JEFworks** [comment]
What is the output of `class(pmat1)`? You can cast it as a matrix via `as.matrix(pmat1)`
