### ISSUE TITLE
scDE is too slow when running large scale datasets.

### ISSUE THREAD

**Issue by iyhaoo** [hms-dbmi/scde#78]
Hi there,
scDE cost more than 3 hrs when input dataset  has more than 3000 cells. I used 24 cores but the processing is still rather long. There is no doubt that scDE provides very accurate results. If the time consumption can be much lower this software will be perfect!

**Comment by JEFworks** [comment]
Indeed, when Dr. Kharchenko and I first developed SCDE, single-cell sequencing via the 96-well plate was still the most common. We knew 384-well plates were coming, but we never expected droplet-based microfluidics to become so readily available and so quickly! 

The Kharchenko lab is actively developing PAGODA2 (as a successor to SCDE) to more appropriately accommodate newer single-cell datasets with 1000s of cells: https://github.com/hms-dbmi/pagoda2 While I am not personally involved in that effort, I'm sure you will be able to find more support on the PAGODA2 github. 

Best,
Jean
